ServerTokens Prod
ServerSignature Off

KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 2

<IfModule mpm_prefork_module>
    StartServers 2
    MinSpareServers 2
    MaxSpareServers 4
    MaxRequestWorkers 8
    MaxConnectionsPerChild 1000
</IfModule>

<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE application/json application/javascript application/xml text/css text/html text/javascript text/plain text/xml
</IfModule>
